=== Mijura/vaccination-app/vaccination-services/immunization-portal-service/src/main/resources/citizen.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.immunization-portal/citizen"
    xmlns="http://www.immunization-portal/citizen">
    <xs:element name="citizen">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="personal_no" type="xs:string"/>
                <xs:element name="first_name" type="xs:string"/>
                <xs:element name="last_name" type="xs:string"/>
                <xs:element name="date_of_birth" type="xs:date"/>
                <xs:element name="gender">
                    <xs:complexType>
                        <xs:choice>
                            <xs:element name="male"/>
                            <xs:element name="female"/>
                        </xs:choice>
                    </xs:complexType>
                </xs:element>
                <xs:element name="email">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="residence" type="xs:string"/>
                <xs:element ref="personal_document"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="personal_document">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="type">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="passaport"/>
                            <xs:enumeration value="identity card"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="document_no" type="xs:string"/>
                <xs:element name="issued_by" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Mijura/vaccination-app/vaccination-services/immunization-portal-service/src/main/resources/citizen1.xml
<?xml version="1.0" encoding="UTF-8"?>
<citizen xmlns="http://www.immunization-portal/citizen"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="citizen.xsd" id="id1">
    <personal_no>2908989710034</personal_no>
    <first_name>Marko</first_name>
    <last_name>Markovic</last_name>
    <date_of_birth>1989-08-29</date_of_birth>
    <gender>
        <male>
        </male>
    </gender>
    <email>marko.markovic@gmail.com</email>
    <residence>Novi Sad</residence>
    <personal_document>
        <type>identity card</type>
        <document_no>0003988789</document_no>
        <issued_by>PU Novi Sad</issued_by>
    </personal_document>
</citizen>
